steps:
# Step 1
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/my-app-vue-dev:$SHORT_SHA', '-t', 'us.gcr.io/$PROJECT_ID/my-app-vue-dev:latest', '.' ]      
#  Step 2
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us.gcr.io/$PROJECT_ID/my-app-vue-dev:$SHORT_SHA', 'us.gcr.io/$PROJECT_ID/my-app-vue-dev:latest', '.' ]
# Step 3
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/developer']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-my-app-vue'
# Step 4
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
    'set', 
    'image', 
    'deployment', 
    'my-app-vue-dev', 
    'my-app-vue-dev=gcr.io/$PROJECT_ID/my-app-vue-dev:$SHORT_SHA'
    ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-my-app-vue'
    # Push the image to Google Container Registry with the ${SHORT_SHA} tag
images: [
  'gcr.io/$PROJECT_ID/my-app-vue-dev:$SHORT_SHA'
  'gcr.io/$PROJECT_ID/my-app-vue-dev:latest'
  ]
